POST {{host}}/app/api/v1/push/taskEnd
Accept: */*
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkZXYiLCJpYXQiOjE1ODYxNDMwMjIsImV4cCI6MTU4ODczNTAyMiwibmJmIjoxNTg2MTQzMDIyLCJ1aWQiOjI1ODcxMDcyfQ.WN6p8yuufpSPmaEBfljGZpN-8i6USqvwvd_AfU5WwfI
Cache-Control: no-cache

ed=gytwVZo5sVX9UDMUEDnZ6iLerk2cNDpY4%2BEOeLDi9aRIdb3yIJHgP4R97iXKamGTESeh2iGA5n0mc7h9kkah5aTUobz%2BkCIlwEkqLvExVrzR1InxdPp%2FW6OkUdqjltj%2F

<> 2020-04-08T104431.200.json
###

